### ISSUE TITLE
DTLA - October 4th, 2016

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#17]
# DTLA
### @ Baldoria in Little Tokyo (243 South San Pedro St., Los Angeles, CA 90012)

http://www.baldoriadtla.com/
https://www.yelp.com/biz/baldoria-los-angeles

Championed by Liz Krane (@learningnerd) this time. Can't wait to see you all there!

**Comment by LearningNerd** [comment]
I shall champion this one :) I'd be happy to. As for places... hmmm. You can find free street parking in the arts district so how about someplace there? Or Little Tokyo nearby. I've been going to Spitz a lot for group meetings over food, and it works great because they have good wifi in addition to good food.

Anyone have suggestions for places to eat though?

**Comment by matikin9** [comment]
Bierbeisl Imbiss (near Guisados)
Baldoria (Little Tokyo)

**Comment by ashwell** [comment]
@LearningNerd I'll add you to the repo so you can update the main ticket with location information.

**Comment by LearningNerd** [comment]
See you all tomorrow at Baldoria! :) I'll be there. I dunno who else is showing up but I'm gonna try to spread the word.

**Comment by matikin9** [comment]
!I'll be there!!  See you soon @LearningNerd !

**Comment by ashwell** [comment]
I hope it went well!
